service:
    name: trible-web-serverless

# Add the serverless-webpack plugin
plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-domain-manager

custom:
    customDomain:
        domainName: trible.com
        basePath: ''
        stage: ${self:provider.stage}
        createRoute53Record: true

provider:
    name: aws
    runtime: nodejs8.10
    region: ap-northeast-2

functions:
    ssr:
        handler: src/server.handler
        events:
            - http:
                  path: /
                  method: ANY
            - http:
                  path: /{any+}
                  method: ANY
